In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7783, 7396, 7214, 4715],
 [7783, 7396, 7214, 7469],
 [7783, 8999, 7214, 6684],
 [1218, 6722, 9278, 3586, 7877],
 [1218, 6722, 9278, 3586, 563],
 [6795, 7783, 7483, 7214, 4004],
 [525, 4767, 7114, 3586]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding

#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7783 7396 7214 4715]
 [   0    0    0    0 7783 7396 7214 7469]
 [   0    0    0    0 7783 8999 7214 6684]
 [   0    0    0 1218 6722 9278 3586 7877]
 [   0    0    0 1218 6722 9278 3586  563]
 [   0    0    0 6795 7783 7483 7214 4004]
 [   0    0    0    0  525 4767 7114 3586]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 526ms/step


array([[[-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,
          0.02008929, -0.03738921, -0.02696579, -0.04451505,
          0.0243984 ,  0.00525581],
        [-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,
          0.02008929, -0.03738921, -0.02696579, -0.04451505,
          0.0243984 ,  0.00525581],
        [-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,
          0.02008929, -0.03738921, -0.02696579, -0.04451505,
          0.0243984 ,  0.00525581],
        [-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,
          0.02008929, -0.03738921, -0.02696579, -0.04451505,
          0.0243984 ,  0.00525581],
        [ 0.0297127 ,  0.00857782, -0.04281909,  0.04956347,
          0.0070038 , -0.00111256,  0.03720417,  0.00275455,
         -0.02932309,  0.04648241],
        [-0.03552324, -0.01851919,  0.0259485 ,  0.01844412,
          0.03241347, -0.00693877,  0.01844634,  0.02995038,
          0.00800891,  0.03329195],
        [ 0.00034962,  0.03387534,  0.03007584,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7783, 7396, 7214, 4715])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 132ms/step


array([[-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,  0.02008929,
        -0.03738921, -0.02696579, -0.04451505,  0.0243984 ,  0.00525581],
       [-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,  0.02008929,
        -0.03738921, -0.02696579, -0.04451505,  0.0243984 ,  0.00525581],
       [-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,  0.02008929,
        -0.03738921, -0.02696579, -0.04451505,  0.0243984 ,  0.00525581],
       [-0.0102331 , -0.0351737 ,  0.01061912, -0.0351304 ,  0.02008929,
        -0.03738921, -0.02696579, -0.04451505,  0.0243984 ,  0.00525581],
       [ 0.0297127 ,  0.00857782, -0.04281909,  0.04956347,  0.0070038 ,
        -0.00111256,  0.03720417,  0.00275455, -0.02932309,  0.04648241],
       [-0.03552324, -0.01851919,  0.0259485 ,  0.01844412,  0.03241347,
        -0.00693877,  0.01844634,  0.02995038,  0.00800891,  0.03329195],
       [ 0.00034962,  0.03387534,  0.03007584,  0.01764491,  0.02745967,
         0.00198245,  0.0480958 , -0.0178463 